-- Reference table for districts. Small and almost never changes, so it is rebuilt on every run.
{{ config(materialized='table') }}

select
    DISTRICT_ID,
    DISTRICT_NAME,
    REGION_NAME,
    NUMBER_OF_INHABITANTS,
    MUNICIPALITIES_UNDER_500_INHABITANTS,
    MUNICIPALITIES_500_TO_1999_INHABITANTS,
    MUNICIPALITIES_2000_TO_9999_INHABITANTS,
    MUNICIPALITIES_OVER_10000_INHABITANTS,
    NUMBER_OF_CITIES,
    PERCENT_OF_URBAN_INHABITANTS,
    AVERAGE_SALARY,
    UNEMPLOYMENT_RATE_1995,
    UNEMPLOYMENT_RATE_1996,
    ENTREPRENEURS_PER_1000_INHABITANTS,
    NUMBER_OF_CRIMES_1995,
    NUMBER_OF_CRIMES_1996,
    LOAD_DATE,
    RECORD_SOURCE
from {{ ref('stg_berka_district') }}