USE ROLE SYSADMIN;

-- USED BY AIRFLOW FOR COPY INTO AND BY DATA BUILD TOOL FOR TRANSFORMATION
CREATE WAREHOUSE IF NOT EXISTS WAREHOUSE_FOR_LOADING_AND_TRANSFORMING
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND=60
    AUTO_RESUME=TRUE
    INITIALLY_SUSPENDED=TRUE
    COMMENT='Compute for data pipelines: loading and data build tool models';


-- USED BY ANALYSTS AND DASHBOARDS THAT READ THE GOLD LAYER
CREATE WAREHOUSE IF NOT EXISTS WAREHOUSE_FOR_REPORTING
    WAREHOUSE_SIZE='XSMALL'
    AUTO_SUSPEND=60
    AUTO_RESUME=TRUE
    INITIALLY_SUSPENDED=TRUE
    COMMENT='Compute for business users and reports on GOLD';

