USE ROLE USERADMIN;

GRANT ROLE BANKING_PIPELINE_SERVICE_ROLE TO ROLE BANKING_DATA_ENGINEER_ROLE;
GRANT ROLE BANKING_DATA_ANALYST_ROLE TO ROLE BANKING_DATA_ENGINEER_ROLE;

GRANT ROLE BANKING_DATA_ENGINEER_ROLE TO ROLE SYSADMIN;

SET current_user_name = CURRENT_USER();
GRANT ROLE BANKING_DATA_ENGINEER_ROLE TO USER IDENTIFIER($current_user_name);

SHOW GRANTS TO ROLE BANKING_DATA_ENGINEER_ROLE;

