USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT USAGE ON WAREHOUSE WAREHOUSE_FOR_REPORTING TO ROLE BANKING_DATA_ANALYST_ROLE;

GRANT USAGE ON DATABASE BANKING_DATA_PLATFORM TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT USAGE ON DATABASE BANKING_DATA_PLATFORM TO ROLE BANKING_DATA_ANALYST_ROLE;

SHOW GRANTS TO ROLE BANKING_DATA_ANALYST_ROLE;