USE ROLE SECURITYADMIN;

GRANT USAGE ON SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_DATA_ANALYST_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_DATA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_DATA_ANALYST_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_DATA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_DATA_ANALYST_ROLE;

SHOW GRANTS TO ROLE BANKING_DATA_ANALYST_ROLE;
SHOW FUTURE GRANTS IN SCHEMA BANKING_DATA_PLATFORM.GOLD;