-- Security role gives access
USE ROLE SECURITYADMIN;

-- Bronze: load raw files from S3
GRANT USAGE ON SCHEMA BANKING_DATA_PLATFORM.BRONZE TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE TABLE ON SCHEMA BANKING_DATA_PLATFORM.BRONZE TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE STAGE ON SCHEMA BANKING_DATA_PLATFORM.BRONZE TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA BANKING_DATA_PLATFORM.BRONZE TO ROLE BANKING_PIPELINE_SERVICE_ROLE;

-- Raw vault: build hubs, links, satellites
GRANT USAGE ON SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE TABLE ON SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE VIEW ON SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT TO ROLE BANKING_PIPELINE_SERVICE_ROLE;

-- Business vault: apply business rules
GRANT USAGE ON SCHEMA BANKING_DATA_PLATFORM.SILVER_BUSINESS_VAULT TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE TABLE ON SCHEMA BANKING_DATA_PLATFORM.SILVER_BUSINESS_VAULT TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE VIEW ON SCHEMA BANKING_DATA_PLATFORM.SILVER_BUSINESS_VAULT TO ROLE BANKING_PIPELINE_SERVICE_ROLE;

-- Gold: build tables for reports
GRANT USAGE ON SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE TABLE ON SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE VIEW ON SCHEMA BANKING_DATA_PLATFORM.GOLD TO ROLE BANKING_PIPELINE_SERVICE_ROLE;

-- Check pipeline access
SHOW GRANTS TO ROLE BANKING_PIPELINE_SERVICE_ROLE;


