USE ROLE ACCOUNTADMIN;

-- ACCOUNTADMIN can create integrations
CREATE STORAGE INTEGRATION IF NOT EXISTS S3_STORAGE_INTEGRATION_FOR_BERKA_RAW_FILES
    TYPE=EXTERNAL_STAGE
    STORAGE_PROVIDER='S3'
    ENABLED=TRUE
    STORAGE_AWS_ROLE_ARN='arn:aws:iam::375553085632:role/snowflake-berka-s3-access-role'
    STORAGE_ALLOWED_LOCATIONS=('s3://berka-banking-data-platform-lora/raw/')
    COMMENT='Connection to the s3 bucket with raw Berka files. Uses an AWS IAM role,no access keys';


GRANT USAGE ON INTEGRATION S3_STORAGE_INTEGRATION_FOR_BERKA_RAW_FILES TO ROLE BANKING_PIPELINE_SERVICE_ROLE;

DESC INTEGRATION S3_STORAGE_INTEGRATION_FOR_BERKA_RAW_FILES;