USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.BRONZE;

CREATE FILE FORMAT IF NOT EXISTS BERKA_CSV_FILE_FORMAT
    TYPE='CSV'
    FIELD_DELIMITER=';'
    SKIP_HEADER=1
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    COMMENT='Format of the Berka CSV files: semicolon delimiter, header row, text in double quotes.';

CREATE STAGE IF NOT EXISTS BERKA_RAW_FILES_STAGE
    URL='s3://berka-banking-data-platform-lora/raw/berka/'
    STORAGE_INTEGRATION=S3_STORAGE_INTEGRATION_FOR_BERKA_RAW_FILES
    FILE_FORMAT=BERKA_CSV_FILE_FORMAT
    COMMENT='Stage for raw Berka files in S3. Airflow uploads files here, Copy into loads them into BRONZE';

List @BERKA_RAW_FILES_STAGE;