USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.BRONZE;

CREATE TABLE IF NOT EXISTS BERKA_CLIENT_RAW (
    CLIENT_ID VARCHAR,
    BIRTH_NUMBER VARCHAR,
    DISTRICT_ID VARCHAR,

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw clients from client.csv (Berka dataset). Loaded 1 to 1, all columns as text.';

ALTER TABLE BERKA_CLIENT_RAW SET COMMENT = 'Raw clients from client.csv (Berka dataset). Loaded 1 to 1, all columns as text.';

SHOW TABLES LIKE 'BERKA_CLIENT_RAW';