USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.BRONZE;

-- TRUNCATE TABLE BERKA_CLIENT_RAW;

COPY INTO BERKA_CLIENT_RAW (
    CLIENT_ID,
    BIRTH_NUMBER,
    DISTRICT_ID,
    SOURCE_FILE_NAME,
    SOURCE_FILE_ROW_NUMBER,
    SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT
        $1,                         
        $2,                       
        $3,                          
        METADATA$FILENAME,           
        METADATA$FILE_ROW_NUMBER,    
        METADATA$FILE_LAST_MODIFIED  
    FROM @BERKA_RAW_FILES_STAGE/client/
)
ON_ERROR = 'ABORT_STATEMENT';


SELECT COUNT(*) AS NUMBER_OF_LOADED_ROWS FROM BERKA_CLIENT_RAW;
SELECT * FROM BERKA_CLIENT_RAW LIMIT 10;