USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.BRONZE;

COPY INTO BERKA_DISTRICT_RAW (
    A1, A2, A3, A4, A5, A6, A7, A8,
    A9, A10, A11, A12, A13, A14, A15, A16,
    SOURCE_FILE_NAME,
    SOURCE_FILE_ROW_NUMBER,
    SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15, $16,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/district/
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS NUMBER_OF_LOADED_ROWS FROM BERKA_DISTRICT_RAW;
SELECT * FROM BERKA_DISTRICT_RAW LIMIT 10;