USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.BRONZE;

CREATE TABLE IF NOT EXISTS BERKA_ACCOUNT_RAW (
    ACCOUNT_ID VARCHAR,
    DISTRICT_ID VARCHAR,
    FREQUENCY VARCHAR,          
    DATE VARCHAR,              

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw accounts from account.csv (Berka dataset). Loaded 1 to 1, all columns as text.';

CREATE TABLE IF NOT EXISTS BERKA_DISP_RAW (
    DISP_ID VARCHAR,
    CLIENT_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    TYPE VARCHAR,            

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw dispositions from disp.csv (Berka dataset). Links clients to accounts. Loaded 1 to 1, all columns as text.';

CREATE TABLE IF NOT EXISTS BERKA_CARD_RAW (
    CARD_ID VARCHAR,
    DISP_ID VARCHAR,
    TYPE VARCHAR,            
    ISSUED VARCHAR,           

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw credit cards from card.csv (Berka dataset). Loaded 1 to 1, all columns as text.';

CREATE TABLE IF NOT EXISTS BERKA_LOAN_RAW (
    LOAN_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    DATE VARCHAR,              
    AMOUNT VARCHAR,
    DURATION VARCHAR,          
    PAYMENTS VARCHAR,          
    STATUS VARCHAR,            

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw loans from loan.csv (Berka dataset). Loaded 1 to 1, all columns as text.';

CREATE TABLE IF NOT EXISTS BERKA_ORDER_RAW (
    ORDER_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    BANK_TO VARCHAR,           
    ACCOUNT_TO VARCHAR,        
    AMOUNT VARCHAR,
    K_SYMBOL VARCHAR,         

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw permanent orders from order.csv (Berka dataset). Loaded 1 to 1, all columns as text.';

CREATE TABLE IF NOT EXISTS BERKA_TRANS_RAW (
    TRANS_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    DATE VARCHAR,               
    TYPE VARCHAR,              
    OPERATION VARCHAR,        
    AMOUNT VARCHAR,
    BALANCE VARCHAR,       
    K_SYMBOL VARCHAR,         
    BANK VARCHAR,           
    PARTNER_ACCOUNT VARCHAR,   

    SOURCE_FILE_NAME VARCHAR,
    SOURCE_FILE_ROW_NUMBER NUMBER,
    SOURCE_FILE_LAST_MODIFIED TIMESTAMP_LTZ,
    LOADED_AT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT='Raw transactions from trans.csv (Berka dataset). Loaded 1 to 1, all columns as text. Column "account" is renamed to PARTNER_ACCOUNT.';