USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.BRONZE;

COPY INTO BERKA_ACCOUNT_RAW (
    ACCOUNT_ID, DISTRICT_ID, FREQUENCY, DATE,
    SOURCE_FILE_NAME, SOURCE_FILE_ROW_NUMBER, SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT $1, $2, $3, $4,
           METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/account/
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BERKA_DISP_RAW (
    DISP_ID, CLIENT_ID, ACCOUNT_ID, TYPE,
    SOURCE_FILE_NAME, SOURCE_FILE_ROW_NUMBER, SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT $1, $2, $3, $4,
           METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/disp/
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BERKA_CARD_RAW (
    CARD_ID, DISP_ID, TYPE, ISSUED,
    SOURCE_FILE_NAME, SOURCE_FILE_ROW_NUMBER, SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT $1, $2, $3, $4,
           METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/card/
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BERKA_LOAN_RAW (
    LOAN_ID, ACCOUNT_ID, DATE, AMOUNT, DURATION, PAYMENTS, STATUS,
    SOURCE_FILE_NAME, SOURCE_FILE_ROW_NUMBER, SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7,
           METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/loan/
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BERKA_ORDER_RAW (
    ORDER_ID, ACCOUNT_ID, BANK_TO, ACCOUNT_TO, AMOUNT, K_SYMBOL,
    SOURCE_FILE_NAME, SOURCE_FILE_ROW_NUMBER, SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
           METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/order/
)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BERKA_TRANS_RAW (
    TRANS_ID, ACCOUNT_ID, DATE, TYPE, OPERATION, AMOUNT, BALANCE, K_SYMBOL, BANK, PARTNER_ACCOUNT,
    SOURCE_FILE_NAME, SOURCE_FILE_ROW_NUMBER, SOURCE_FILE_LAST_MODIFIED
)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
           METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @BERKA_RAW_FILES_STAGE/trans/
)
ON_ERROR = 'ABORT_STATEMENT';


SELECT 'BERKA_CLIENT_RAW'   AS TABLE_NAME, COUNT(*) AS LOADED_ROWS, 5369    AS EXPECTED_ROWS FROM BERKA_CLIENT_RAW
UNION ALL SELECT 'BERKA_DISTRICT_RAW', COUNT(*), 77      FROM BERKA_DISTRICT_RAW
UNION ALL SELECT 'BERKA_ACCOUNT_RAW',  COUNT(*), 4500    FROM BERKA_ACCOUNT_RAW
UNION ALL SELECT 'BERKA_DISP_RAW',     COUNT(*), 5369    FROM BERKA_DISP_RAW
UNION ALL SELECT 'BERKA_CARD_RAW',     COUNT(*), 892     FROM BERKA_CARD_RAW
UNION ALL SELECT 'BERKA_LOAN_RAW',     COUNT(*), 682     FROM BERKA_LOAN_RAW
UNION ALL SELECT 'BERKA_ORDER_RAW',    COUNT(*), 6471    FROM BERKA_ORDER_RAW
UNION ALL SELECT 'BERKA_TRANS_RAW',    COUNT(*), 1056320 FROM BERKA_TRANS_RAW;


-- LIST @BANKING_DATA_PLATFORM.BRONZE.BERKA_RAW_FILES_STAGE;