USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

INSERT INTO HUB_CLIENT (CLIENT_HASH_KEY, CLIENT_ID, LOAD_DATE, RECORD_SOURCE)
SELECT
    MD5(UPPER(TRIM(source_clients.CLIENT_ID))) AS CLIENT_HASH_KEY,
    TRIM(source_clients.CLIENT_ID) AS CLIENT_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    MIN(source_clients.SOURCE_FILE_NAME) AS RECORD_SOURCE
FROM BANKING_DATA_PLATFORM.BRONZE.BERKA_CLIENT_RAW AS source_clients
WHERE source_clients.CLIENT_ID IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM HUB_CLIENT AS existing_clients
        WHERE existing_clients.CLIENT_HASH_KEY = MD5(UPPER(TRIM(source_clients.CLIENT_ID)))
    )
GROUP BY TRIM(source_clients.CLIENT_ID);

SELECT COUNT(*) AS NUMBER_OF_CLIENTS_IN_HUB FROM HUB_CLIENT;
SELECT * FROM HUB_CLIENT LIMIT 5;