USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;


CREATE TABLE IF NOT EXISTS SAT_CLIENT_DETAILS (
    CLIENT_HASH_KEY VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_LTZ NOT NULL,
    HASH_DIFF VARCHAR(32) NOT NULL,
    RECORD_SOURCE VARCHAR NOT NULL,

    BIRTH_NUMBER VARCHAR,
    DISTRICT_ID VARCHAR,

    CONSTRAINT PK_SAT_CLIENT_DETAILS PRIMARY KEY (CLIENT_HASH_KEY, LOAD_DATE),
    CONSTRAINT FK_SAT_CLIENT_DETAILS_HUB_CLIENT FOREIGN KEY (CLIENT_HASH_KEY) REFERENCES
    HUB_CLIENT (CLIENT_HASH_KEY)
)
COMMENT = 'Data Vault satellite for client details (birth number, district). Keeps full history. Insert only.';