USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

INSERT INTO SAT_CLIENT_DETAILS (CLIENT_HASH_KEY, LOAD_DATE, HASH_DIFF, RECORD_SOURCE, BIRTH_NUMBER, DISTRICT_ID)
WITH newest_client_rows_from_bronze AS (
    SELECT
        MD5(UPPER(TRIM(CLIENT_ID))) AS CLIENT_HASH_KEY,
        MD5(CONCAT_WS('||',
            COALESCE(TRIM(BIRTH_NUMBER), ''),
            COALESCE(TRIM(DISTRICT_ID), '')
        ))                          AS HASH_DIFF,
        SOURCE_FILE_NAME            AS RECORD_SOURCE,
        BIRTH_NUMBER,
        DISTRICT_ID
    FROM BANKING_DATA_PLATFORM.BRONZE.BERKA_CLIENT_RAW
    WHERE CLIENT_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRIM(CLIENT_ID)
        ORDER BY SOURCE_FILE_LAST_MODIFIED DESC, SOURCE_FILE_ROW_NUMBER DESC
    ) = 1
),
current_client_rows_in_satellite AS (
    SELECT CLIENT_HASH_KEY, HASH_DIFF
    FROM SAT_CLIENT_DETAILS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CLIENT_HASH_KEY
        ORDER BY LOAD_DATE DESC
    ) = 1
)
SELECT
    bronze_rows.CLIENT_HASH_KEY,
    CURRENT_TIMESTAMP(),
    bronze_rows.HASH_DIFF,
    bronze_rows.RECORD_SOURCE,
    bronze_rows.BIRTH_NUMBER,
    bronze_rows.DISTRICT_ID
FROM newest_client_rows_from_bronze AS bronze_rows
LEFT JOIN current_client_rows_in_satellite AS satellite_rows
    ON satellite_rows.CLIENT_HASH_KEY = bronze_rows.CLIENT_HASH_KEY
WHERE satellite_rows.CLIENT_HASH_KEY IS NULL             
   OR satellite_rows.HASH_DIFF <> bronze_rows.HASH_DIFF;   

SELECT COUNT(*) AS NUMBER_OF_ROWS_IN_SATELLITE FROM SAT_CLIENT_DETAILS;
SELECT * FROM SAT_CLIENT_DETAILS LIMIT 5;