USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

CREATE TABLE IF NOT EXISTS HUB_ACCOUNT (
    ACCOUNT_HASH_KEY VARCHAR(32) NOT NULL,
    ACCOUNT_ID VARCHAR NOT NULL,
    LOAD_DATE TIMESTAMP_LTZ NOT NULL,
    RECORD_SOURCE VARCHAR NOT NULL,

    CONSTRAINT PK_HUB_ACCOUNT PRIMARY KEY (ACCOUNT_HASH_KEY)
)

COMMENT='Data Vault hub for accounts. One row for each unique account ID. Insert only.';