USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

INSERT INTO HUB_ACCOUNT (ACCOUNT_HASH_KEY, ACCOUNT_ID, LOAD_DATE, RECORD_SOURCE)
SELECT
    MD5(UPPER(TRIM(source_accounts.ACCOUNT_ID))) AS ACCOUNT_HASH_KEY,
    TRIM(source_accounts.ACCOUNT_ID) AS ACCOUNT_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    MIN(source_accounts.SOURCE_FILE_NAME) AS RECORD_SOURCE
FROM BANKING_DATA_PLATFORM.BRONZE.BERKA_ACCOUNT_RAW AS source_accounts
WHERE source_accounts.ACCOUNT_ID IS NOT NULL
    AND NOT EXISTS (
        SELECT 1 
        FROM HUB_ACCOUNT AS existing_accounts
        WHERE existing_accounts.ACCOUNT_HASH_KEY=
        MD5(UPPER(TRIM(source_accounts.ACCOUNT_ID)))
    )
GROUP BY TRIM(source_accounts.ACCOUNT_ID);

SELECT COUNT(*) AS NUMBER_OF_ACCOUNTS_IN_HUB FROM HUB_ACCOUNT;
SELECT * FROM HUB_ACCOUNT LIMIT 5;
