USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

CREATE TABLE IF NOT EXISTS SAT_ACCOUNT_DETAILS (
    ACCOUNT_HASH_KEY  VARCHAR(32)   NOT NULL, 
    LOAD_DATE         TIMESTAMP_LTZ NOT NULL, 
    HASH_DIFF         VARCHAR(32)   NOT NULL,   
    RECORD_SOURCE     VARCHAR       NOT NULL,  

    DISTRICT_ID       VARCHAR,                 
    FREQUENCY         VARCHAR,                  
    DATE              VARCHAR,                

    CONSTRAINT PK_SAT_ACCOUNT_DETAILS PRIMARY KEY (ACCOUNT_HASH_KEY, LOAD_DATE),
    CONSTRAINT FK_SAT_ACCOUNT_DETAILS_HUB_ACCOUNT FOREIGN KEY (ACCOUNT_HASH_KEY) REFERENCES HUB_ACCOUNT (ACCOUNT_HASH_KEY)
)
COMMENT = 'Data Vault satellite for account details (district, statement frequency, opening date). Keeps full history. Insert only.';