USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

INSERT INTO SAT_ACCOUNT_DETAILS (ACCOUNT_HASH_KEY, LOAD_DATE, HASH_DIFF, RECORD_SOURCE, DISTRICT_ID, FREQUENCY, DATE)
WITH newest_account_rows_from_bronze AS (
    SELECT
        MD5(UPPER(TRIM(ACCOUNT_ID))) AS ACCOUNT_HASH_KEY,
        MD5(CONCAT_WS('||',
            COALESCE(TRIM(DISTRICT_ID), ''),
            COALESCE(TRIM(FREQUENCY), ''),
            COALESCE(TRIM(DATE), '')
        )) AS HASH_DIFF,
        SOURCE_FILE_NAME AS RECORD_SOURCE,
        DISTRICT_ID,
        FREQUENCY,
        DATE
    FROM BANKING_DATA_PLATFORM.BRONZE.BERKA_ACCOUNT_RAW
    WHERE ACCOUNT_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRIM(ACCOUNT_ID)
        ORDER BY SOURCE_FILE_LAST_MODIFIED DESC, SOURCE_FILE_ROW_NUMBER DESC
    ) = 1
),
current_account_rows_in_satellite AS (
    SELECT ACCOUNT_HASH_KEY, HASH_DIFF
    FROM SAT_ACCOUNT_DETAILS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ACCOUNT_HASH_KEY
        ORDER BY LOAD_DATE DESC
    ) = 1
)
SELECT
    bronze_rows.ACCOUNT_HASH_KEY,
    CURRENT_TIMESTAMP(),
    bronze_rows.HASH_DIFF,
    bronze_rows.RECORD_SOURCE,
    bronze_rows.DISTRICT_ID,
    bronze_rows.FREQUENCY,
    bronze_rows.DATE
FROM newest_account_rows_from_bronze AS bronze_rows
LEFT JOIN current_account_rows_in_satellite AS satellite_rows
    ON satellite_rows.ACCOUNT_HASH_KEY = bronze_rows.ACCOUNT_HASH_KEY
WHERE satellite_rows.ACCOUNT_HASH_KEY IS NULL
   OR satellite_rows.HASH_DIFF <> bronze_rows.HASH_DIFF;

SELECT COUNT(*) AS NUMBER_OF_ROWS_IN_SATELLITE FROM SAT_ACCOUNT_DETAILS;