USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

CREATE TABLE IF NOT EXISTS LINK_CLIENT_ACCOUNT (
    CLIENT_ACCOUNT_HASH_KEY  VARCHAR(32)   NOT NULL,  
    CLIENT_HASH_KEY          VARCHAR(32)   NOT NULL,   
    ACCOUNT_HASH_KEY         VARCHAR(32)   NOT NULL,  
    LOAD_DATE                TIMESTAMP_LTZ NOT NULL,  
    RECORD_SOURCE            VARCHAR       NOT NULL, 

    CONSTRAINT PK_LINK_CLIENT_ACCOUNT PRIMARY KEY (CLIENT_ACCOUNT_HASH_KEY),
    CONSTRAINT FK_LINK_CLIENT_ACCOUNT_HUB_CLIENT  FOREIGN KEY (CLIENT_HASH_KEY)  REFERENCES HUB_CLIENT (CLIENT_HASH_KEY),
    CONSTRAINT FK_LINK_CLIENT_ACCOUNT_HUB_ACCOUNT FOREIGN KEY (ACCOUNT_HASH_KEY) REFERENCES HUB_ACCOUNT (ACCOUNT_HASH_KEY)
)
COMMENT = 'Data Vault link between clients and accounts. One account can have more than one client. Insert only.';