USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

INSERT INTO LINK_CLIENT_ACCOUNT (CLIENT_ACCOUNT_HASH_KEY, CLIENT_HASH_KEY, ACCOUNT_HASH_KEY, LOAD_DATE, RECORD_SOURCE)
SELECT
    MD5(UPPER(TRIM(source_dispositions.CLIENT_ID)) || '||' || UPPER(TRIM(source_dispositions.ACCOUNT_ID))) AS CLIENT_ACCOUNT_HASH_KEY,
    MD5(UPPER(TRIM(source_dispositions.CLIENT_ID)))   AS CLIENT_HASH_KEY,
    MD5(UPPER(TRIM(source_dispositions.ACCOUNT_ID)))  AS ACCOUNT_HASH_KEY,
    CURRENT_TIMESTAMP()                               AS LOAD_DATE,
    MIN(source_dispositions.SOURCE_FILE_NAME)         AS RECORD_SOURCE
FROM BANKING_DATA_PLATFORM.BRONZE.BERKA_DISP_RAW AS source_dispositions
WHERE source_dispositions.CLIENT_ID IS NOT NULL
  AND source_dispositions.ACCOUNT_ID IS NOT NULL
  AND NOT EXISTS (
        SELECT 1
        FROM LINK_CLIENT_ACCOUNT AS existing_pairs
        WHERE existing_pairs.CLIENT_ACCOUNT_HASH_KEY =
              MD5(UPPER(TRIM(source_dispositions.CLIENT_ID)) || '||' || UPPER(TRIM(source_dispositions.ACCOUNT_ID)))
  )
GROUP BY TRIM(source_dispositions.CLIENT_ID), TRIM(source_dispositions.ACCOUNT_ID);

SELECT COUNT(*) AS NUMBER_OF_CLIENT_ACCOUNT_PAIRS FROM LINK_CLIENT_ACCOUNT;