USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

CREATE TABLE IF NOT EXISTS SAT_CLIENT_ACCOUNT_DETAILS (
    CLIENT_ACCOUNT_HASH_KEY  VARCHAR(32) NOT NULL,  
    LOAD_DATE TIMESTAMP_LTZ NOT NULL,  
    HASH_DIFF VARCHAR(32) NOT NULL,  
    RECORD_SOURCE VARCHAR NOT NULL,   

    DISP_ID VARCHAR,     
    TYPE VARCHAR,              

    CONSTRAINT PK_SAT_CLIENT_ACCOUNT_DETAILS PRIMARY KEY (CLIENT_ACCOUNT_HASH_KEY, LOAD_DATE),
    CONSTRAINT FK_SAT_CLIENT_ACCOUNT_DETAILS_LINK FOREIGN KEY (CLIENT_ACCOUNT_HASH_KEY) REFERENCES LINK_CLIENT_ACCOUNT (CLIENT_ACCOUNT_HASH_KEY)
)
COMMENT = 'Data Vault satellite on the client and account link: role of the client (owner or disponent). Keeps full history. Insert only.';