USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

INSERT INTO SAT_CLIENT_ACCOUNT_DETAILS (CLIENT_ACCOUNT_HASH_KEY, LOAD_DATE, HASH_DIFF, RECORD_SOURCE, DISP_ID, TYPE)
WITH newest_disposition_rows_from_bronze AS (
    SELECT
        MD5(UPPER(TRIM(CLIENT_ID)) || '||' || UPPER(TRIM(ACCOUNT_ID))) AS CLIENT_ACCOUNT_HASH_KEY,
        MD5(CONCAT_WS('||',
            COALESCE(TRIM(DISP_ID), ''),
            COALESCE(TRIM(TYPE), '')
        )) AS HASH_DIFF,
        SOURCE_FILE_NAME AS RECORD_SOURCE,
        DISP_ID,
        TYPE
    FROM BANKING_DATA_PLATFORM.BRONZE.BERKA_DISP_RAW
    WHERE CLIENT_ID IS NOT NULL
      AND ACCOUNT_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRIM(CLIENT_ID), TRIM(ACCOUNT_ID)
        ORDER BY SOURCE_FILE_LAST_MODIFIED DESC, SOURCE_FILE_ROW_NUMBER DESC
    ) = 1
),
current_pair_rows_in_satellite AS (
    SELECT CLIENT_ACCOUNT_HASH_KEY, HASH_DIFF
    FROM SAT_CLIENT_ACCOUNT_DETAILS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CLIENT_ACCOUNT_HASH_KEY
        ORDER BY LOAD_DATE DESC
    ) = 1
)
SELECT
    bronze_rows.CLIENT_ACCOUNT_HASH_KEY,
    CURRENT_TIMESTAMP(),
    bronze_rows.HASH_DIFF,
    bronze_rows.RECORD_SOURCE,
    bronze_rows.DISP_ID,
    bronze_rows.TYPE
FROM newest_disposition_rows_from_bronze AS bronze_rows
LEFT JOIN current_pair_rows_in_satellite AS satellite_rows
    ON satellite_rows.CLIENT_ACCOUNT_HASH_KEY = bronze_rows.CLIENT_ACCOUNT_HASH_KEY
WHERE satellite_rows.CLIENT_ACCOUNT_HASH_KEY IS NULL
   OR satellite_rows.HASH_DIFF <> bronze_rows.HASH_DIFF;

SELECT COUNT(*) AS NUMBER_OF_ROWS_IN_SATELLITE FROM SAT_CLIENT_ACCOUNT_DETAILS;

SELECT
    hub_account.ACCOUNT_ID,
    COUNT(*) AS NUMBER_OF_CLIENTS
FROM LINK_CLIENT_ACCOUNT AS link
JOIN HUB_ACCOUNT AS hub_account
    ON hub_account.ACCOUNT_HASH_KEY = link.ACCOUNT_HASH_KEY
GROUP BY hub_account.ACCOUNT_ID
HAVING COUNT(*) > 1
ORDER BY hub_account.ACCOUNT_ID
LIMIT 10;


-- Raw vault reconciliation: rows in each table and accounts with more than one client.
SELECT 'HUB_CLIENT'                 AS TABLE_NAME, COUNT(*) AS NUMBER_OF_ROWS, 5369 AS EXPECTED_ROWS FROM HUB_CLIENT
UNION ALL SELECT 'SAT_CLIENT_DETAILS',          COUNT(*), 5370 FROM SAT_CLIENT_DETAILS
UNION ALL SELECT 'HUB_ACCOUNT',                 COUNT(*), 4500 FROM HUB_ACCOUNT
UNION ALL SELECT 'SAT_ACCOUNT_DETAILS',         COUNT(*), 4500 FROM SAT_ACCOUNT_DETAILS
UNION ALL SELECT 'LINK_CLIENT_ACCOUNT',         COUNT(*), 5369 FROM LINK_CLIENT_ACCOUNT
UNION ALL SELECT 'SAT_CLIENT_ACCOUNT_DETAILS',  COUNT(*), 5369 FROM SAT_CLIENT_ACCOUNT_DETAILS
UNION ALL SELECT 'ACCOUNTS WITH TWO CLIENTS',   COUNT(*), 869
          FROM (SELECT ACCOUNT_HASH_KEY FROM LINK_CLIENT_ACCOUNT GROUP BY ACCOUNT_HASH_KEY HAVING COUNT(*) > 1);