USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS BANKING_PIPELINE_SERVICE_USER
    TYPE = SERVICE
    DEFAULT_ROLE = BANKING_PIPELINE_SERVICE_ROLE
    DEFAULT_WAREHOUSE = WAREHOUSE_FOR_LOADING_AND_TRANSFORMING
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4qZTBe+QuUXh3jnIB6eZOSexpGc/BIXaEgn7W+zeaMKMQq3O71dar3THTix4Mf6KFAxNAPX1CuNs6cAIlVV2gvgr9UZYmRTJAHYy+LfQX3Il4zelooP+r21fKXgQ6d1oMZKUF+D5TlBTwqZsrN6mO9MFpfBcHDgo6QP17bJAh2is+wx+92a19/NQwvFgzvcckJ8jNjaOWxN+nT7n1nF5wP6a/+8E2mM1XQ9FUeLpVvDRq3CEgfnnQghKdreqT4rz1Rf+IXfSlZ1XQVou8heFNjgHT44RY+yZYpyNZKXnE2WtYtqgyGYZUxKJ0pyrFmnTsqxqZ9tNx0HdSrnWcYvdqQIDAQAB'
    COMMENT = 'Service user for dbt and Airflow. Signs in with a key pair only. Uses the pipeline role.';

GRANT ROLE BANKING_PIPELINE_SERVICE_ROLE TO USER BANKING_PIPELINE_SERVICE_USER;

DESC USER BANKING_PIPELINE_SERVICE_USER;