USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;


DROP TABLE IF EXISTS SAT_CLIENT_ACCOUNT_DETAILS;
DROP TABLE IF EXISTS LINK_CLIENT_ACCOUNT;
DROP TABLE IF EXISTS SAT_ACCOUNT_DETAILS;
DROP TABLE IF EXISTS HUB_ACCOUNT;
DROP TABLE IF EXISTS SAT_CLIENT_DETAILS;
DROP TABLE IF EXISTS HUB_CLIENT;

SELECT COUNT(*) FROM BANKING_DATA_PLATFORM.SILVER_RAW_VAULT.HUB_CLIENT;

SHOW TABLES IN SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

SHOW TABLES IN SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;