USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS BANKING_DATA_PLATFORM.DATA_QUALITY
    COMMENT = 'Stores results of data quality tests: rows that failed a dbt test. Written by the pipeline role only.';

USE ROLE SECURITYADMIN;

GRANT USAGE ON SCHEMA BANKING_DATA_PLATFORM.DATA_QUALITY TO ROLE BANKING_PIPELINE_SERVICE_ROLE;
GRANT CREATE TABLE ON SCHEMA BANKING_DATA_PLATFORM.DATA_QUALITY TO ROLE BANKING_PIPELINE_SERVICE_ROLE;

SHOW GRANTS ON SCHEMA BANKING_DATA_PLATFORM.DATA_QUALITY;