USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;
USE SCHEMA BANKING_DATA_PLATFORM.SILVER_RAW_VAULT;

SELECT
    hub_loan.LOAN_ID,
    hub_account.ACCOUNT_ID,
    sat.AMOUNT,
    sat.STATUS
FROM HUB_LOAN AS hub_loan
JOIN SAT_LOAN_DETAILS AS sat
    ON sat.LOAN_HASH_KEY = hub_loan.LOAN_HASH_KEY
JOIN LINK_LOAN_ACCOUNT AS link
    ON link.LOAN_HASH_KEY = hub_loan.LOAN_HASH_KEY
JOIN HUB_ACCOUNT AS hub_account
    ON hub_account.ACCOUNT_HASH_KEY = link.ACCOUNT_HASH_KEY
WHERE sat.STATUS IN ('B', 'D')
ORDER BY sat.STATUS, hub_loan.LOAN_ID;