USE ROLE BANKING_PIPELINE_SERVICE_ROLE;
USE WAREHOUSE WAREHOUSE_FOR_LOADING_AND_TRANSFORMING;

-- Full history of client 1.
SELECT
    hub.CLIENT_ID,
    sat.LOAD_DATE,
    sat.DISTRICT_ID,
    sat.RECORD_SOURCE
FROM BANKING_DATA_PLATFORM.SILVER_RAW_VAULT.HUB_CLIENT AS hub
JOIN BANKING_DATA_PLATFORM.SILVER_RAW_VAULT.SAT_CLIENT_DETAILS AS sat
    ON sat.CLIENT_HASH_KEY = hub.CLIENT_HASH_KEY
WHERE hub.CLIENT_ID = '1'
ORDER BY sat.LOAD_DATE;